# Generated by Django 2.2.7 on 2019-12-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpus',
            old_name='diabled',
            new_name='disabled',
        ),
        migrations.AddField(
            model_name='corpus',
            name='add_governor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpus',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='len',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
