# Generated by Django 3.0 on 2019-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_auto_20191202_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='initial_query',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='initial_table',
            field=models.TextField(null=True),
        ),
    ]
