# Generated by Django 3.0 on 2019-12-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_auto_20191205_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name_plural': 'Corpora'},
        ),
        migrations.AddField(
            model_name='corpus',
            name='language_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explore.Language'),
        ),
    ]
