# Generated by Django 3.0 on 2019-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_auto_20191211_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
