# Generated by Django 3.0.5 on 2020-05-31 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_auto_20200525_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='language',
            field=models.ForeignKey(choices=[('nl', 'Dutch'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('de_frak', 'German (Fraktur)'), ('el', 'Greek'), ('it', 'Italian'), ('pt', 'Portuguese'), ('es', 'Spanish')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='explore.Language'),
        ),
    ]
