# Generated by Django 3.0.5 on 2020-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0016_language_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='drop_columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DropColumn',
        ),
    ]
