# Generated by Django 3.0.5 on 2020-07-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0017_auto_20200531_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='length',
        ),
    ]
