# Generated by Django 3.0.7 on 2020-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0018_remove_corpus_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='example_concordance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
