# Generated by Django 3.0.7 on 2020-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0019_corpus_example_concordance'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='epub',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
