# Generated by Django 3.0.7 on 2020-08-08 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0020_corpus_epub'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('indices', models.TextField()),
                ('position', models.TextField(null=True)),
                ('query', models.CharField(max_length=300)),
                ('regex', models.BooleanField()),
                ('target', models.CharField(max_length=50)),
                ('inverse', models.BooleanField()),
                ('idx', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explore.SearchResult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('slug', 'user', 'idx')},
            },
        ),
    ]
