# Generated by Django 3.0.7 on 2020-08-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_auto_20200808_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
