# Generated by Django 3.0.7 on 2020-08-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0023_searchresult_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('idx', models.IntegerField()),
                ('show', models.CharField(max_length=300)),
                ('subcorpora', models.CharField(max_length=300)),
                ('relative', models.CharField(max_length=20, null=True)),
                ('keyness', models.CharField(max_length=2, null=True)),
                ('sort', models.CharField(max_length=10, null=True)),
                ('produced_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explore.SearchResult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('slug', 'user', 'idx')},
            },
        ),
    ]
