# Generated by Django 3.0.7 on 2020-08-23 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0024_tableresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
