# Generated by Django 3.0.6 on 2020-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0002_auto_20200511_1717"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("path", models.TextField()),
                ("name", models.CharField(max_length=200)),
                ("num", models.IntegerField()),
            ],
        ),
    ]
