# Generated by Django 3.0.6 on 2020-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20200525_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrupdate',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
