# Generated by Django 3.0.5 on 2020-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_tif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrupdate',
            name='previous',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
