# Generated by Django 3.0.5 on 2020-07-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_ocrupdate_previous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrupdate',
            options={'verbose_name': 'OCR texts', 'verbose_name_plural': 'OCR texts'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFs'},
        ),
        migrations.AlterModelOptions(
            name='tif',
            options={'verbose_name': 'TIF', 'verbose_name_plural': 'TIFs'},
        ),
    ]
