# Generated by Django 3.0.5 on 2020-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_auto_20200719_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrupdate',
            name='username',
            field=models.CharField(default='danny', max_length=200),
            preserve_default=False,
        ),
    ]
